/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomDropdown: typeof import('./src/components/CustomDropdown.vue')['default']
    DelaySlider: typeof import('./src/components/delay-slider/index.vue')['default']
    FluidCursor: typeof import('./src/components/FluidCursor.vue')['default']
    Key: typeof import('./src/components/key/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    Result: typeof import('./src/components/result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderNumber: typeof import('./src/components/slider-number/index.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TColorPicker: typeof import('tdesign-vue-next')['ColorPicker']
    TColorPickerPanel: typeof import('tdesign-vue-next')['ColorPickerPanel']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    THeader: typeof import('tdesign-vue-next')['Header']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
